---
title: "CA_comparing_aridity"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(raster)
library(sf)
library(rgdal)
library(here)
library(tidyverse)
library(tictoc)

# library with all the change comparison functions
source(here("comparing_individual_layers","change_functions.R"))
```


##  Exploring aridity changes CA, 2008 to 2019

```{r}
year<- 2008
ca_arid8 <- raster(here("combine_layers",
                                   "ca_matched_layers_timeseries",
                                   "aridity",
                                   paste("ca_arid_match_",year,".tif",sep="")))
year<-2019
ca_arid19 <- raster(here("combine_layers",
                                   "ca_matched_layers_timeseries",
                                   "aridity",
                                   paste("ca_arid_match_",year,".tif",sep="")))

```

```{r}
# finding number of pixels changing from categories in arid8 to categories in arid19
tic('ca change_mtx time')
ca_mtx_arid_8_19 <-change_mtx(ca_arid8, ca_arid19)
toc()
# ca change_mtx time: 2840.274 sec elapsed
```


```{r}

cats_names <- c('desert','dry','moist')
colnames(ca_mtx_arid_8_19) <- cats_names
rownames(ca_mtx_arid_8_19) <- cats_names
ca_mtx_arid_8_19
```

```{r}
# create oredered data frame from change_mtx
df_arid_8_19 <-change_df(ca_mtx_arid_8_19, keep_equals = FALSE)
df_arid_8_19
```

```{r}
cats_names <- c('desert','dry','moist')
tic('raster_change_mtx (california aridity)')
ca_results <- raster_change_mtx(ca_arid8, c(1,2,3), cats_names,
                                ca_arid19, c(1,2,3), cats_names)
toc()
```


```{r}
ca_results
plot(ca_results)
```

```{r}
# save rasters

# for(i in 1:9){
#   name <- paste(names(ca_results)[i],".tif",sep="")
#   writeRaster(ca_results[[i]], here("comparing_individual_layers",
#                                     "ca_aridity_comparisons",
#                                     name))  
# }
```

### Mapping with CA boundary

```{r}
ca_shp <- readOGR(here("shapefiles",
                       "ca-state-boundary",
                       "CA_State_TIGER2016.shp"))

ca_shp <- spTransform(ca_shp, crs(result_mtx))
```

```{r}
names <- names(ca_results)

for (i in 1:9){
  plot(ca_results[[i]], main=names[i] )
  plot(ca_shp,add=TRUE)
}

```

```{r}
par(mfrow = c(3, 3))
names <- names(ca_results)

for (i in 1:9){
  plot(ca_results[[i]], 
       main=names[i], 
       axes=FALSE,
       legend=FALSE)
  plot(ca_shp,add=TRUE)
}
```


