---
title: "climate_layer"
author: "Carmen Galaz-García"
output: html_document
---
```{r setup,  warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(raster)
library(rgdal)
library(tidyverse)
library(here)
library(sf) 

library(tictoc)
```


```{r}
# ---- NOTES ABOUT FILES ----
# 2010 - 2019 decade folders only has files until 2018
#------------------------------------------------------------------------------

#----- generate file name
file_name <- function(tminmax,year,i){
  file <- paste("wc2.1_2.5m_",tminmax,"_",year,"-", sep="")
  if(i<10){
    file <- paste(file,'0',sep="")
  }
  file <- paste(file,i,".tif",sep="")
  return(file)
}

#----- generate folder name
folder_name <- function(tminmax,year){
  decade <- year - (year%%10)
  folder <- paste("wc2.1_2.5m_",tminmax,"_",decade,"-",decade+9,sep="")
  return(folder)
}


#----- clipping and writing monthly rasters
# year = year to compute average temperature
# bbox = bounding box of area of interest
# returns the average of all (avg min monthly temps) and (avg max monthly temps) 
yearly_avg <- function(year,bbox){
  months <- stack()
  for(i in c(1:12)){
     month_rast <- raster(here("raw_data",
                               "world_clim_historical_monthly_data",
                               "min_avg_temp",
                               folder_name("tmin",year),
                               file_name("tmin",year,i)))
     month_rast <- crop(x= month_rast, y=bbox)
     months <- addLayer(months,month_rast)
  }
  for(i in c(1:12)){
     month_rast <- raster(here("raw_data",
                               "world_clim_historical_monthly_data",
                               "max_avg_temp",
                               folder_name("tmax",year),
                               file_name("tmax",year,i)))
     month_rast <- crop(x= month_rast, y=bbox)
     months <- addLayer(months,month_rast)
  }
  return(mean(months))
}

#------ create average over decade
# calculate avg temperature over 30 years before year
# ex: year= 2001, then average over [2000,1971]
decade_avg <- function(year,bbox){
  years <- stack()
  for( i in c((year-30):(year-1))){
    years<- addLayer(years, yearly_avg(i,bbox))
  }
  return(mean(years))
}


```



```{r}
#----- CA shapefile & bounding box ------
ca_shp <- readOGR(here("shapefiles",
                       "ca-state-boundary",
                       "CA_State_TIGER2016.shp"))
temp <- raster(here("raw_data","world_clim_historical_monthly_data",
                        "max_avg_temp",
                        "wc2.1_2.5m_tmax_1970-1979",
                         "wc2.1_2.5m_tmax_1970-01.tif"))
ca_shp <- spTransform(ca_shp, crs(temp))
rm(temp)

bbox <- st_bbox(ca_shp)

```

```{r, eval=FALSE}
# ---- test & timing  ---
tic("create 1 year avg")
year_avg_temp <- yearly_avg(year,bbox)
toc()  # ~4 sec


tic("decade avg")
temp_avg_2008 <- decade_avg(2008,bbox)
toc()  # ~2 min

```


```{r, eval=FALSE}
# ---- create climate rasters for 2001, 2008, 2019 -----

ca_clim_2001 <- mask(decade_avg(2001,bbox),ca_shp)
#writeRaster(ca_clim_2001, filename=here("ca_subsets","avg_temp_30years","ca_clim_2001.tif"))

ca_clim_2008 <- mask(decade_avg(2008,bbox),ca_shp)
#writeRaster(ca_clim_2008, filename=here("ca_subsets","avg_temp_30years","ca_clim_2008.tif"))

ca_clim_2019 <- mask(decade_avg(2019,bbox),ca_shp)
#writeRaster(ca_clim_2019, filename=here("ca_subsets","avg_temp_30years","ca_clim_2019.tif"))

```
