---
title: "comparing_SB_landcovers"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(raster)
library(rgdal)
library(tidyverse)
library(here)
library(sf)
```


```{r}
# 11 : open water          (10)
# 12 : perennial ice/snow  (1)
# 21-24 : developed        (2)
# 31 : barren              (3)
# 41-43 : forest           (4)
# 51,52 : shrubland        (5)
# 71-74 : grassland        (7)
# 81,82: cropland          (8)
# 90,95: wetland           (9)

lc_2008 <- raster(here("sb_layers","sb_landcover_2008.tif"))
lc_2019 <- raster(here("sb_layers","sb_landcover_2019.tif"))
plot(lc_2008, xlab= "2008")
plot(lc_2019, xlab="2019")
```




```{r}

# --- comparing 2008 and 2019 ---

change <- (lc_2008 - lc_2019)
change[change==0] <- NA
plot(change)
unique(change)
```


```{r}

subset <- lc_2008
i=2
subset[subset!=i] <- NA # select category to analyze for change
#plot(subset)

change <- subset - lc_2019

df1 <- data.frame(freq(change)) %>% 
  filter(is.na(value)==FALSE)

value <- setdiff( seq(i-1,i-10,by=-1) ,df1[,1])
count <- rep(0,each=length(value))
df2 <- data.frame(value,count)
rm(value,count)

all_change <- bind_rows(df1,df2) %>% 
  arrange(desc(value))
all_change[,2]
```



```{r}
# see how category i in A changes in B
change_i <- function(rasterA,i,rasterB){
  change <- rasterA
  change[change!=i] <- NA     # select category to analyze for change
  change <- change - rasterB  # change between A_i and B (change can equal 0)
  # if categories for rasters = {1,...,k}, then change categories = {i-1,...,1-k} 
  # ex: a pixel in change with value i-1 means A changed from category i to category 1
  
  df1 <- data.frame(freq(change)) %>% #count number of pixels in each change category
    filter(is.na(value)==FALSE)
  
  # -- extend dataframe to include categories A_i did not change to --
  value <- setdiff( seq(i-1,i-10,by=-1) ,df1[,1]) # A_i did not change to any of these categories
  count <- rep(0,each=length(value))
  df2 <- data.frame(value,count)

  all_change <- bind_rows(df1,df2) %>% 
    arrange(desc(value))  # recover categories in raster from order
  return(all_change[,2])
}

change_i(lc_2008,2,lc_2019)

```



```{r}

change_mtx <- matrix(NA, 10, 10)  ## set up an empty matrix to fill
for (i in 1:10) {
  ## fill i-th row of the matrix
  change_mtx[i,] <- change_i(lc_2008,i,lc_2019)
  }
```

