---
title: "landcover_create_layer"
output: html_document
---
# Landcover (2008 and 2019)

https://www.mrlc.gov/data?f%5B0%5D=year%3A2008

Legends:
https://www.mrlc.gov/data/legends/national-land-cover-database-2019-nlcd2019-legend

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE)
library(raster)
library(rgdal)
library(tidyverse)
library(here)
library(sf) 

library(tictoc)
```

```{r}
# ---- prep functions ----

crop_shape <- function(ref_raster , shape){
  new_shape <- spTransform(shape, crs(ref_raster))
  return(mask(crop(x= ref_raster, y=st_bbox(new_shape)),new_shape))
}

# ----------------------------------------------------------------------
# Aggregate land cover classifications

# 11 : open water          (10)
# 12 : perennial ice/snow  (1)
# 21-24 : developed        (2)
# 31 : barren              (3)
# 41-43 : forest           (4)
# 51,52 : shrubland        (5)
# 71-74 : grassland        (7)
# 81,82: cropland          (8)
# 90,95: wetland           (9)

landcover_regions <- function(lc_raster){
  thresh<- cbind( c(1:9)*10, c(2:10)*10, c(1:9)) 
  thresh[1,1] <-12

  new_raster <- lc_raster
  new_raster[new_raster == 11] <- 10

  return(reclassify(new_raster,thresh, right=FALSE))
}
# ----------------------------------------------------------------------
# check classification is ok:
# lc_2019 <- raster(here("raw_data",
#               "nlcd_2019_land_cover_l48_20210604",
#               "nlcd_2019_land_cover_l48_20210604.img"))
# 
# ca_lc_2019 <- crop_shape(lc_2019,ca_shp)
# ca_lc_regions_2019 <- landcover_regions(ca_lc_2019)
# diff <- ca_lc_2019-(ca_lc_regions_2019*10)
# unique(diff) # should -89 and numbers from 0 to 9
```



```{r}
#----- 2001 landcover ----
lc_2001 <- raster(here("raw_data",
                       "nlcd_2001_land_cover_l48_20210604",
                       "nlcd_2001_land_cover_l48_20210604.img"))
#----- CA shapefile ------
ca_shp <- readOGR(here("shapefiles",
                       "ca-state-boundary",
                       "CA_State_TIGER2016.shp"))


```


```{r, eval=FALSE}
# ----- Mask US land cover to CA

# ---- US land cover raster
# GDALinfo(here("raw_data",
#               "nlcd_2008_land_cover_l48_20210604",
#               "nlcd_2008_land_cover_l48_20210604.img"))

# land_cover <- raster(here("raw_data",
#               "nlcd_2008_land_cover_l48_20210604",
#               "nlcd_2008_land_cover_l48_20210604.img"))


#----- CA shapefile ------
# ca_shp <- readOGR(here("shapefiles",
#                        "ca-state-boundary",
#                        "CA_State_TIGER2016.shp"))

# --- mask
#ca_shp <- spTransform(ca_shp, crs(land_cover))
#ca_land_cover <- mask(crop(x= land_cover, y=st_bbox(ca_shp)),ca_shp)
#writeRaster(ca_land_cover, filename=here(ca_subsets","landcover","ca_land_cover_2008.tif")  )
#rm(land_cover)


```


```{r}
# 11 : open water          (10)
# 12 : perennial ice/snow  (1)
# 21-24 : developed        (2)
# 31 : barren              (3)
# 41-43 : forest           (4)
# 51,52 : shrubland        (5)
# 71-74 : grassland        (7)
# 81,82: cropland          (8)
# 90,95: wetland           (9)
  
ca_land_cover <- raster(here("ca_subsets","landcover","ca_landcover_2008.tif"))

thresh<- cbind( c(1:9)*10, c(2:10)*10, c(1:9)) 
thresh[1,1] <-12

ca_lc_regions <- ca_land_cover
ca_lc_regions[ca_lc_regions == 11] <- 10

ca_water_10 <- ca_lc_regions

ca_lc_regions <- reclassify(ca_water_10,thresh, right=FALSE)
unique(ca_lc_regions)
plot(ca_lc_regions)
#writeRaster(ca_lc_regions, filename=here("ca_subsets","landcover","ca_landcover_regions.tif")  )
```




```{r}
lc_2019 <- raster(here("raw_data",
              "nlcd_2019_land_cover_l48_20210604",
              "nlcd_2019_land_cover_l48_20210604.img"))

ca_shp <- spTransform(ca_shp, crs(lc_2019))
ca_lc_2019 <- crop_shape(lc_2019,ca_shp)

writeRaster(ca_lc_2019, filename=here("ca_subsets","landcover","ca_landcover_2019.tif"))

ca_lc_regions_2019 <- landcover_regions(ca_lc_2019)
writeRaster(ca_lc_regions_2019, filename=here("ca_subsets","landcover","ca_landcover_regions_2019.tif"))
```

