---
title: "sb_ecosystems"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(raster)
library(rgdal)
library(tidyverse)
library(here)
library(sf)
```

```{r}
sb_shp <- readOGR(here("shapefiles",
                       "sb-county-boundary",
                       "data",
                       "commondata",
                       "county_boundaries",
                       "SB_only.shp"))

# --- open rasters ---
aridity <- raster(here("ca_subsets","aridity","ca_aridity_regions.tif"))
temp <- raster(here("ca_subsets","avg_temp_30years","ca_30yr_temp_regions.tif"))
landforms <- raster(here("ca_subsets","landforms","ca_landforms.tif"))
landcover <- raster(here("ca_subsets","landcover","ca_landcover_regions.tif"))

# --- clip rasters ---
sb_shp <- spTransform(sb_shp, crs(aridity))
sb_bbox <-st_bbox(sb_shp)

aridity <- mask(crop(x= aridity, y=sb_bbox), sb_shp)
temp <- mask(crop(x= temp, y=sb_bbox), sb_shp)
landforms <- mask(crop(x= landforms, y=sb_bbox), sb_shp)
rm(sb_bbox)

sb_shp <- spTransform(sb_shp, crs(landcover))
landcover <- mask(crop(x=landcover, y = st_bbox(sb_shp)),sb_shp)
```


```{r}
# --- match rasters ---
aridity <- projectRaster(from = aridity, to= landcover, method='ngb')
temp <- projectRaster(from = temp, to= landcover, method='ngb')
landforms <- projectRaster(from = landforms, to= landcover, method='ngb')

# writeRaster(aridity, filename=here("sb_layers","sb_aridity.tif"))
# writeRaster(temp, filename=here("sb_layers","sb_temp.tif"))
# writeRaster(landcover, filename=here("sb_layers","sb_landcover.tif"))
```

```{r}
# relabeling landforms raster. 

plot(landforms)
unique(landforms)

thresh<- matrix(c(26,1,
                  27,2,
                  31,3,
                  32,4), nrow=4,byrow=TRUE)
landforms <- reclassify(landforms,thresh) 
rm(thresh)

unique(landforms)
plot(landforms)

#writeRaster(landforms, filename=here("sb_layers","sb_landforms.tif"))

```

```{r}
# ----- USGS SB ecosystems -----

usgs_ecos <- raster(here('ca_subsets','usgs_ecosystems_2009','usgs_ca_ecos.tif'))
sb_shp <- spTransform(sb_shp, crs(usgs_ecos))

usgs_ecos <-  mask(crop(x= usgs_ecos, y=st_bbox(sb_shp)), sb_shp)
#plot(usgs_ecos)
usgs_ecos <- projectRaster(from = usgs_ecos, to= landcover, method='ngb')
#plot(usgs_ecos)
writeRaster(usgs_ecos, filename=here("sb_layers","sb_usgs_ecos.tif"))
```

```{r}
# ------  2019 landcover layer -----
lc_2019 <- raster(here("ca_subsets","landcover","ca_landcover_regions_2019.tif"))

sb_shp <- spTransform(sb_shp, crs(lc_2019))
lc_2019 <- mask(crop(x=lc_2019, y = st_bbox(sb_shp)),sb_shp)

writeRaster(lc_2019, filename=here("sb_layers","sb_landcover_2019.tif"))
```

