---
title: "Santa Barbara fires"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(raster)  # add packages in this order
library(sf)
library(rgdal)

library(here)
library(tidyverse)
library(janitor)


# library with all the change comparison functions
source(here("comparing_individual_layers","change_functions.R"))
```

```{r}

# -------------------------------------------------------------
# open biomass layers
path <- here(
  "comparing_individual_layers",
  "biomass",
  "biomass")

biom1<- raster(paste(path,"_2001.tif", sep=""))
biom8<- raster(paste(path,"_2008.tif", sep=""))
biom19<- raster(paste(path,"_2019.tif", sep=""))

# -------------------------------------------------------------
# read in fire perimeters geometries
path <- here(
  "comparing_individual_layers",
  "biomass",
  "Fire Perimeters, Santa Barbara County, 2018 Update",
  "data",
  "v10",
  "environment.gdb")

raw_fires <- st_read(dsn= path,as_tibble=FALSE) %>% 
  clean_names

fires <- raw_fires %>% 
  select(year,state, fire_name, Shape ) %>% 
  filter(state == "CA") %>% 
  select(!state)

fires <- st_transform(fires,crs(biom19))
rm(raw_fires)

# -------------------------------------------------------------
# open SB shapefile
sb_shp <- st_read(here("shapefiles",
                       "sb-county-boundary",
                       "data",
                       "commondata",
                       "county_boundaries",
                       "SB_only.shp"))

sb_shp <- st_transform(sb_shp,crs(biom19))
# -------------------------------------------------------------

rm(path)

```


```{r}
# -------------------------------------------------------------

# returns data frame
bio_change <- function(rast1, rast2, change){
  change_rast <- rast2 - rast1
  if(change == 1){
    change_rast[change_rast < 1] <- NA}
  if(change == 0 ){
    change_rast[change_rast != 0] <- NA}
  if(change == -1){
    change_rast[change_rast>-1] <- NA}

  df <- raster::rasterToPoints(change_rast) %>% as.data.frame()
  return(df)
}
# -------------------------------------------------------------

# select fires that happened on from <= year < to
fire_subset <- function(fires,from,to){
  subset <- fires %>% 
    filter(from <= year, year <= to)
  return(subset)
}

plot_bio_chng_fires <- function(change, 
                                change_df, yr1, yr2, 
                                fires,
                                sb_shp){
  if(change == 1){
    title <- paste("Increase in biomass (",yr1," - ", yr2,")", sep = "") }
  if(change == 0){
    title <- paste("Stable biomass (",yr1," - ", yr2,")", sep = "") }
  if(change == -1){
    title <- paste("Decrease in biomass (",yr1," - ", yr2,")", sep = "") }
  
  graph <- ggplot() +
    geom_raster(data = change_df, aes(x = x, y = y), fill="gray50")+
    geom_sf(data=sb_shp, alpha=0, color="black")+
    geom_sf(data = fires, alpha=0.2, aes(color = year, fill=year), size = 0.3) +
    labs(title = title)+
    theme_bw()
  
  return(graph)
}
```



```{r}

ggplot() +
  geom_sf(data = fires, alpha=0.3, aes(color = year, fill=year), size = 0.3) +
  geom_sf(data=sb_shp, alpha=0, color="black")+
  theme_bw()
```

```{r}
# *************************************************************
## Looking at specific change in biomass 
# *************************************************************

# Biomass loss 2008 to 2019 (largest three)

forest_2_grass <- raster_change_ij(biom8, 4, biom19, 2)
shrub_2_grass <- raster_change_ij(biom8, 3, biom19, 2)
forest_2_shrub <- raster_change_ij(biom8, 4, biom19, 3)

# raster to data frame
f2g_df <- raster::rasterToPoints(forest_2_grass) %>%
  as.data.frame()
s2g_df <- raster::rasterToPoints(shrub_2_grass) %>%
  as.data.frame()
f2s_df <- raster::rasterToPoints(forest_2_shrub) %>%
  as.data.frame()

rm(forest_2_grass,shrub_2_grass,forest_2_shrub)
```


```{r}
# -------------------------------------------------------------
ggplot() +
  geom_raster(data = f2g_df, aes(x = x, y = y, fill = layer), color="blue")+
  geom_sf(data=sb_shp, alpha=0, color="black")+
  geom_sf(data = fires, alpha=0.3, aes(color = year, fill=year), size = 0.3) +
  labs(title = "Forest 2 grass (2008 - 2019)")+
  theme_bw()+
  theme(legend.position = "none")
  
```


```{r}
# -------------------------------------------------------------
ggplot() +
  geom_raster(data = f2s_df, aes(x = x, y = y, fill = layer), color="blue")+
  geom_sf(data=sb_shp, alpha=0, color="black")+
  geom_sf(data = fires, alpha=0.3, aes(color = year, fill=year), size = 0.3) +
  labs(title = "Forest 2 shrub (2008 - 2019)")+
  theme_bw()+
  theme(legend.position = "none")
  
```


```{r}
# -------------------------------------------------------------
ggplot() +
  geom_raster(data = s2g_df, aes(x = x, y = y, fill = layer), color="blue")+
  geom_sf(data=sb_shp, alpha=0, color="black")+
  geom_sf(data = fires, alpha=0.3, aes(color = year, fill=year), size = 0.3) +
  labs(title = "Shrub 2 grass (2008 - 2019)")+
  theme_bw()+
  theme(legend.position = "none")
```


```{r}
# *************************************************************
##       Decrease in biomass 
# *************************************************************
plot_bio_chng_fires(-1, 
                    bio_change(biom1,biom8,-1), 
                    2001, 2008,
                    fire_subset(fires,1999,2019),
                    sb_shp )

plot_bio_chng_fires(-1, 
                    bio_change(biom8,biom19,-1), 
                    2008, 2019,
                    fire_subset(fires,1999,2019),
                    sb_shp )
```


```{r}
# *************************************************************
##       Stable biomass 
# *************************************************************
plot_bio_chng_fires(0, 
                    bio_change(biom1,biom8,0), 
                    2001, 2008,
                    fire_subset(fires,1999,2008),
                    sb_shp )

plot_bio_chng_fires(0, 
                    bio_change(biom8,biom19,0), 
                    2008, 2019,
                    fire_subset(fires,2006,2019),
                    sb_shp )
```

```{r}
# *************************************************************
##       Increase in biomass 
# *************************************************************

plot_bio_chng_fires(1, 
                    bio_change(biom1,biom8,1), 
                    2001, 2008,
                    fire_subset(fires,1999,2018),
                    sb_shp )

plot_bio_chng_fires(1, 
                    bio_change(biom8,biom19,1), 
                    2008, 2019,
                    fire_subset(fires,1999,2018),
                    sb_shp )
```



```{r}
# *************************************************************
##       2001 - 2019
# *************************************************************

plot_bio_chng_fires(-1, 
                    bio_change(biom1,biom19,-1), 
                    2001, 2019,
                    fire_subset(fires,1999,2018),
                    sb_shp )

plot_bio_chng_fires(1, 
                    bio_change(biom1,biom19,1), 
                    2001, 2019,
                    fire_subset(fires,1999,2018),
                    sb_shp )
```


