---
title: "eco_land_units"
output: html_document
---

```{r}
library(here)
library(raster)
library(sf)
library(tictoc)
```

```{r}
combine_layers <- function(year){

  root <- here('combine_layers','matched_layers_timeseries')
  clim <- raster(paste(root,'/climate/ca_clim_match_',year,'.tif',sep=""))
  arid <- raster(paste(root,'/aridity/ca_arid_match_',year,'.tif',sep=""))
  forms <- raster(paste(root,'/landforms/ca_landforms_match.tif',sep=""))
  lcover <- raster(paste(root,'/landcover/ca_landcover_regions_match_',year,'.tif',sep=""))
  
  combined <- clim + 10*arid + 100*forms + 1000*lcover
  
  # mask to CA 
  #ca_shp <- readOGR(here("shapefiles","ca-state-boundary", "CA_State_TIGER2016.shp"))
  #ca_shp <- spTransform(ca_shp, crs(lcover))
  
  #return(mask(combined,ca_shp))
  return(combined)
  
}
```

```{r}
tic('combining layers')
elu_2001 <- combine_layers(2001)
toc()
```

```{r}
plot(elu_2001)
```

```{r}
tic('combining layers')
writeRaster(elu_2001,here("combine_layers","elu_2001.tif"))
toc()
```

```{r}
tic('combining layers')
elu_2008 <- combine_layers(2008)
writeRaster(elu_2008,here("combine_layers","elu_2008.tif"))
toc()

elu_2019 <- combine_layers(2019)
writeRaster(elu_2019,here("combine_layers","elu_2019.tif"))

plot(elu_2008)
plot(elu_2019)
```