---
title: "comparing_elu_maps"
output: html_document
---

```{r}
library(raster)
library(sf)

```


## CREATE CHANGE MATRIX

```{r}

# see how category i in raster A changes in raster B  
# B has categories catsB = (b_1,...,b_n)  (b_i < b_(i+1) integers)
# ** modified from landcover_comparing_SB.rmd **

change_i <- function(rasterA,i, rasterB,catsB){
  change <- rasterA
  change[change!=i] <- NA     # select category A_i
  change <- change - rasterB  # change between A_i and B (change can equal 0)
  # if categories for rasters = (b_1,...,b_n}, then change categories = (i-b_1,...,i-b_n)
  # ex: a pixel in change with value i-b_1 means A changed from category i to category b_1
  
  df1 <- data.frame(freq(change)) %>% #count number of pixels in each change category
    filter(is.na(value)==FALSE)       # remove NAs
  
  # -- extend dataframe to include categories A_i did not change to --
  value <- setdiff( i-catsB ,df1[,1]) # A_i did not change to any of these categories
  count <- rep(0,each=length(value))
  df2 <- data.frame(value,count)

  all_change <- bind_rows(df1,df2) %>% 
    arrange(desc(value))  # recover categories in raster from order
  return(all_change[,2])
}

# ------------------------------------------------------------------------------------
# Returns matrix M = (M_ij)
# M_ij = # pixels changed from category i in rasterA to category j in rasterB
# ** modified from landcover_comparing_SB.rmd **

change_mtx <- function(rasterA, rasterB){
  
  catsA = unique(rasterA)
  catsB = unique(rasterB)
  
  # set up an empty matrix to fill
  m = length(catsA)
  n = length(catsB)
  mtx <- matrix(NA, m, n) 
  for (i in 1:m) {
    ## fill i-th row of the matrix
    mtx[i,] <- change_i(rasterA,catsA[i], rasterB,catsB)
  } 
  rownames(mtx) <- catsA
  colnames(mtx) <- catsB
  return(mtx)
}

```


## TURN CHANGE MATRIX INTO DATAFRAME

```{r}
# ** modified from landcover_comparing_SB.rmd **
change_df <- function(change_mtx, keep_equals=FALSE){
  
  change_tofrom <- data.frame(matrix(ncol=3,nrow=0, dimnames=list(NULL, c("from", "to", "num_pixels"))))
  m <- nrow(change_mtx)
  n <- ncol(change_mtx)
  for(i in 1:m){
    from_name <- rownames(change_mtx)[i]
    for(j in 1:n){
      to_name <- colnames(change_mtx)[j]
      if(from_name == to_name){
        if(keep_equals==TRUE){
          change_tofrom[nrow(change_tofrom)+1,] <- list(from_name,to_name,change_mtx[i,j])    
        } 
      }
      else{
        change_tofrom[nrow(change_tofrom)+1,] <- list(from_name,to_name,change_mtx[i,j])    
        }
    }
  }
  return(change_tofrom)
}
```


```{r}
#elu1 <- raster(here("combine_layers","elu_SB","elu_2001_SB.tif"))
elu8 <- raster(here("combine_layers","elu_SB","elu_2008_SB.tif"))
elu19 <- raster(here("combine_layers","elu_SB","elu_2019_SB.tif"))

cats8 <- unique(elu8)
cats19 <- unique(elu19)
```


```{r}
trial <- change_mtx(elu8,elu19,cats8,cats19)
trial
```


```{r}
lc_2008 <- raster(here("sb_layers","sb_landcover_2008.tif"))
lc_2019 <- raster(here("sb_layers","sb_landcover_2019.tif"))

check <- change_mtx(lc_2008,lc_2019, unique(lc_2008),unique(lc_2019))
check  # good! agrees with previous LULC comparison and gets rid of empty categories
```

```{r}
change_df(check) %>% arrange(desc(num_pixels))
change_df(check,keep_equals = TRUE) %>% arrange(desc(num_pixels))
```

```{r}
change_df(trial) %>% arrange(desc(num_pixels))

```
```{r}
changedf_819 <- change_df(trial) %>% arrange(desc(num_pixels))
changedf_819$from <- as.integer(changedf_819$from)
changedf_819$to <- as.integer(changedf_819$to)
changedf_819
write.csv(changedf_819, here("combine_layers","change_08_to_19.csv"))
```


```{r}
df1 <- changedf_819
df1 %>%
  filter(num_pixels!=0) %>%
  mutate( diff_clim = abs(to%%10 - from%%10)) %>% 
  mutate( diff_arid = (to - to%%10)%%100 - (from - from%%10)%%100 ) %>% # negative => more arid
  #mutate( diff_forms = abs((to - to%%100)%%1000 - (from - from%%100)%%1000 )) # landform layer does not change over years
  mutate( diff_lulc = abs((to - to%%1000)%%10000 - (from - from%%1000)%%10000 )) %>% 
  select(!diff_clim) %>% 
  filter(diff_arid!=0, diff_lulc!=0)


# 1 : perennial ice/snow  (12)
# 2 : developed           (21 - 24)
# 3 : barren              (31)
# 4 : forest           (41-43)
# 5 : shrubland        (51,52)
# 7 : grassland        (71-74)
# 8 : cropland          (81,82)
# 9 : wetland           (90,95)
# 10 : open water         (11)
```


```{r}
ca_elu8 <- raster(here("combine_layers","elu_2008.tif"))
ca_elu19 <- raster(here("combine_layers","elu_2019.tif"))

ca_check <- change_mtx(ca_elu8,ca_elu19)
ca_changedf <- change_df(ca_check) %>% arrange(desc(num_pixels))
ca_changedf$from <- as.integer(ca_changedf$from)
ca_changedf$to <- as.integer(ca_changedf$to)

write.csv(ca_changedf, here("combine_layers","ca_change_08_to_19.csv"))
# *** had to run this in the server ***
```

